### PR TITLE
Upgrade to kotlin 1.3.30

### PR DESCRIPTION
**Pull request by rpalcolea**

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
No idea why Travis failed. We'll have to run that again.

**Comment by JLLeitschuh** [comment]
@Tapchicoma Any ideas on why Travis is being finicky?

**Comment by Tapchicoma** [comment]
@JLLeitschuh no idea, will test it locally and try to reproduce.

**Comment by tasomaniac** [comment]
I believe you need to also upgrade the version of the ktlint used in sample project dependencies.

**Comment by Tapchicoma** [comment]
@rpalcolea thank you for your contribution! Have to fix kotlin update in a separate PR #235 (problem was in kotlin "konan" plugin), so closing this PR.

**Comment by rpalcolea** [comment]
thanks folks!

**Pull request closed without merging**
