### PR TITLE
Update ktlint to 0.36

### PR DESCRIPTION
**Pull request by friederbluemle**

### CODE REVIEW

**Comment by nikiJava** [comment]
Please, merge this PR, cause new ktlint version has some important fixes.
https://github.com/pinterest/ktlint/issues/625

**Comment by JLLeitschuh** [comment]
This is causing test failures. Can you look into this?
https://github.com/JLLeitschuh/ktlint-gradle/pull/327/checks?check_run_id=404304250#step:6:73

**Comment by friederbluemle** [comment]
Hi, yeah, I saw the test failure, will try to check later today. Sorry for not responding sooner!

**Comment by Tapchicoma** [comment]
@nikiJava you could just set it via extension configuration, check "version" property: https://github.com/JLLeitschuh/ktlint-gradle#configuration

@friederbluemle sorry, ktlint is already updated on `master` to `0.36.0`: https://github.com/JLLeitschuh/ktlint-gradle/blob/1cca1437e423d30c23f1876a19de19645987c74d/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintExtension.kt#L36

Unfortunately it is not yet published, but it will be soon!

**Comment by friederbluemle** [comment]
🤦‍♂ Of course.. my bad, sorry about that.

Looking forward to the new version. 👍

**Pull request closed without merging**
