### PR TITLE
Add Version Catalog Setup Instructions in README

### PR DESCRIPTION
**Pull request by soleil-colza**
This update supplements the documentation by adding instructions for configuring the Ktlint Gradle plugin using a version catalog. 

Since using version catalogs is now recommended officially and is used by default in newly generated projects, this addition provides essential guidance for both Groovy and Kotlin DSL users, making it easier to integrate the plugin into modern project setups.

### CODE REVIEW

**Comment by wakingrufus** [comment]
Thanks for this!
Please add an entry to the CHANGELOG (our PR checks require this), and I will be happy to merge it.

**Comment by wakingrufus** [comment]
your build failures are due to https://github.com/JLLeitschuh/ktlint-gradle/issues/771 I will update you when this is resolved

**Comment by soleil-colza** [comment]
> Thanks for this! Please add an entry to the CHANGELOG (our PR checks require this), and I will be happy to merge it.

Thank you so much for the rapid action @wakingrufus and apologies for not adding it to the CHANGELOG, I've added it now so could you please check it out when you're available? 
And noted about #771 !

**Review by JLLeitschuh — APPROVED** [review]
This seems like a reasonable change. Thanks!

**Review by JLLeitschuh — APPROVED** [review]
LGTM!

**Pull request merged**
