### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by migueln1987**
Add current version to README.md. Can I get a notification when an update is released? Apparently someone can copy and paste one change in one file five times.

### CODE REVIEW

**Comment by migueln1987** [comment]
Can't* sorry typo. I'm already watching for new releases. Don't make Kotlin into another JavaScript...

Screenshot 2024-03-22 at 10 47 08 PM

**Comment by JLLeitschuh** [comment]
Ideally, we would have some sort of automation to automatically update the README for every release.

**Comment by JLLeitschuh** [comment]
This project comes to mind: https://github.com/diffplug/freshmark

**Comment by StefMa** [comment]
@JLLeitschuh the latest version is already part of the Readme as a badge to the plugin portal. Isn't this enough to merge this PR? 🤔

**Comment by JLLeitschuh** [comment]
I think I'd ideally like to make as much of our release process automated as possible. This change isn't heading in that direction so I'm going to close it.

Thank you for your contribution though!

**Pull request closed without merging**
