### PR TITLE
Set default KtLint version to '0.41.0'.

### LINKED ISSUE #458: Cannot choose between the following variants of com.pinterest:ktlint:0.41.0
I have upgraded `ktlint` from `0.40.0` to `0.41.0`. However, I am getting below error when I run `./gradlew ktlintCheck`. There is no change in my config between two versions. How do I fix this? Thank you.

```
* What went wrong:
Execution failed for task ':loadKtlintReporters'.
> Could not resolve all files for configuration ':ktlint'.
   > Could not resolve com.pinterest:ktlint:0.41.0.
     Required by:
         project :
      > Cannot choose between the following variants of com.pinterest:ktlint:0.41.0:
          - runtimeElements
          - shadowRuntimeElements
        All of them match the consumer attributes:
          - Variant 'runtimeElements' capability com.pinterest:ktlint:0.41.0:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.jvm.version '8' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
                  - Provides org.jetbrains.kotlin.localToProject 'public' but the consumer didn't ask for it
                  - Provides org.jetbrains.kotlin.platform.type 'jvm' but the consumer didn't ask for it
          - Variant 'shadowRuntimeElements' capability com.pinterest:ktlint:0.41.0:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'shadowed' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
```

Sorry, since it is a private repo, I am posting the relative parts here.

### ktlint configuration

```groovy
ktlint {
   android = true
   enableExperimentalRules = true
   ignoreFailures = false
   version = "0.41.0"
   filter {
       exclude("**/generated/**", "**/build/**")
   }
   reporters {
       reporter "html"
   }
}
```

### .editorconfig

```editorconfig
# EditorConfig: http://editorconfig.org
root=true

[*]
insert_final_newline=true
disabled_rules=import-ordering,chain-wrapping,experimental:spacing-between-declarations-with-comments

[*.{kt,kts}]
max_line_length=120

[**/test/**.kt]
max_line_length=off
```

### Working env

- ktlint version: 0.41.0
- ktlint-gradle plugin version: 10.0.0
- Gradle: 6.8.3
- Android Studio: 4.1.3

### PR DESCRIPTION
**Pull request by Tapchicoma**
Use KtLint classes when doing serialization/deserialization and KtLint version is '0.41.0'.

Fixes #458

### CODE REVIEW

**Review by JLLeitschuh — APPROVED** [review]
LGTM!

**Comment by mshearer123** [comment]
Hi @JLLeitschuh Will this be released soon?

thanks

**Comment by nuhkoca** [comment]
@mshearer123 in case you missed, [10.1.0](https://github.com/JLLeitschuh/ktlint-gradle/releases/tag/v10.1.0) was released.

**Comment by mshearer123** [comment]
Amazing thanks

**Pull request merged**
