### PR TITLE
Update ktlint to 0.40.0.

### PR DESCRIPTION
**Pull request by utwyko**
See https://github.com/pinterest/ktlint/releases/tag/0.40.0

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Looks like this change introduces some test failures. PTAL

**Comment by utwyko** [comment]
> Looks like this change introduces some test failures. PTAL

Huh seems I ran the tests incorrectly locally before pushing. I'll take a look later this week!

**Comment by utwyko** [comment]
Tests are failing due to https://github.com/pinterest/ktlint/issues/997. Will update this PR when a version of ktlint is released including that fix.

**Comment by Tapchicoma** [comment]
Probably better to add empty `.editorconfig` then to wait for a new release.

**Pull request merged**
