### PR TITLE
Replicate TravisCI in Github actions.

### PR DESCRIPTION
**Pull request by Tapchicoma**

### CODE REVIEW

**Comment by Tapchicoma** [comment]
To run Github actions on forked PR - creator of this PR should also get beta access to actions and enable them on the fork :thinking:

**Comment by JLLeitschuh** [comment]
@Tapchicoma With actions pretty much out of beta, you should now have access.

**Comment by Tapchicoma** [comment]
Github Actions still not usable as they not triggered for PRs from a forked repos :man_facepalming: 

https://github.community/t5/GitHub-Actions/Github-Workflow-not-running-from-pull-request-from-forked/td-p/32979

**Comment by JLLeitschuh** [comment]
That's interesting. Regardless, can we merge this in and see what it does?

**Comment by Tapchicoma** [comment]
I will merge it. Let us see how it behaves. Once it is working for PRs from forked repositories - other parts of travis-ci configuration could be migrated.

**Pull request merged**
